### ISSUE TITLE
Invalid CRN and account number empty

### ISSUE THREAD

**Issue by nepal-git** [arpandaze/nepseutils#12]
Some account saved in nepseutils shows: **Apply failed! Status code: 409, Message: b'{"message":"Invalid CRN provided.","status":"CONFLICT","statusCode":409}'** 
even if its the correct CRN
It used to apply successfully previously.
And one account from Mega Capital shows : **Apply failed! Status code: 400, Message: b'[{"fieldType":"accountNumber","message":"Account number cannot be empty.","messageTemplate":"{account.number.notnull}","path":"MeroShareApplicantFormViewModel.applyShare.arg0.accountNumber"}]'**

**Comment by arpandaze** [comment]
Just tested and didn't have the issue with my accounts so I am unable to debug. Have you tried by removing and adding back accounts?

**Comment by nepal-git** [comment]
yes i tried

**Comment by nepal-git** [comment]
@arpandaze Account number not fetching problem during adding account is with Nepal Investment Mega Bank
I tried with different accounts of this bank multiple times
Please look into this

**Comment by arpandaze** [comment]
Problem might have started after the merger of Investment and Mega bank. I don't have account of NIMB bank so, I am unable to debug it. If you are willing to provide me your account for testing, I might be able to fix it. Please contact through my email.

**Comment by arpandaze** [comment]
Unable to reproduce.

**Comment by arpandaze** [comment]
Unable to reproduce.
