### ISSUE TITLE
IPO Result from "My ASBA"

### ISSUE THREAD

**Issue by arpandaze** [arpandaze/nepseutils#13]
IPO result can also be obtained from My ASBA section inside meroshare. This might be useful to those who don't have azcaptcha token.

**Comment by nepal-git** [comment]
Encountering IndexError: list index out of range for some issues in ipo result from My ASBA

**Comment by arpandaze** [comment]
Resolved in v0.4.0 (ca411d45563d94ff366937f4654df4baf2897498)
